from dataiku.sql import Dialects

SUPPORTS_FULL_OUTER_JOIN = "supports_full_outer_join"
SUPPORTS_WITH_CLAUSE = "supports_with_clause"
SUPPORTS_RAND = "supports_rand"


SUPPORTED_DIALECTS = {
    Dialects.POSTGRES: {SUPPORTS_FULL_OUTER_JOIN: True, SUPPORTS_WITH_CLAUSE: True, SUPPORTS_RAND: False},
    Dialects.SNOWFLAKE: {SUPPORTS_FULL_OUTER_JOIN: True, SUPPORTS_WITH_CLAUSE: True, SUPPORTS_RAND: True},
    Dialects.BIGQUERY: {SUPPORTS_FULL_OUTER_JOIN: True, SUPPORTS_WITH_CLAUSE: True, SUPPORTS_RAND: True},
    Dialects.SQLSERVER: {SUPPORTS_FULL_OUTER_JOIN: True, SUPPORTS_WITH_CLAUSE: False, SUPPORTS_RAND: False},
    Dialects.SYNAPSE: {SUPPORTS_FULL_OUTER_JOIN: True, SUPPORTS_WITH_CLAUSE: False, SUPPORTS_RAND: False},
}
